---
# Redis defaults
redis_version: "7"
redis_port: 6379
redis_tls_port: 6380
redis_bind: "127.0.0.1"
redis_data_dir: /home/mkanavi/docker/iacgenie/data/redis
redis_maxmemory: 512mb
redis_maxmemory_policy: allkeys-lru
redis_maxmemory_samples: 5
redis_maxclients: 10000
redis_aof_enabled: "yes"
redis_aof_rewrite_percentage: 100
redis_aof_rewrite_min_size: "64mb"
redis_rdb_save_1: "900"
redis_rdb_save_1_count: "1"
redis_rdb_save_2: "300"
redis_rdb_save_2_count: "10"
redis_rdb_save_3: "60"
redis_rdb_save_3_count: "10000"
redis_timeout: 300
redis_tcp_backlog: 511
redis_tcp_keepalive: 300
redis_loglevel: notice
redis_databases: 16
redis_slowlog_threshold: 10000
redis_slowlog_max_entries: 128
redis_tls_enabled: true
redis_password: "CHANGE_ME_IN_VAULT"
redis_backup_password: "CHANGE_ME_IN_VAULT"
