---
- name: Reload docker compose
  ansible.builtin.command: docker compose -f /home/mkanavi/docker/iacgenie/docker-compose.yml up -d keycloak
  args:
    chdir: /home/mkanavi/docker/iacgenie
  changed_when: true
