/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
    "./services/**/*.{js,ts,jsx,tsx}",
    "./store/**/*.{js,ts,jsx,tsx}",
    "./App.tsx",
    "./index.tsx",
  ],
  theme: {
    extend: {
      colors: {
        orange: {
          100: '#FFF7ED',
          500: '#f97316',
          600: '#ea580c',
        },
        // Slate color palette for dark theme (from design_system.md)
        slate: {
          50: '#f8fafc',
          100: '#f1f5f9',
          200: '#e2e8f0',
          300: '#cbd5e1',
          400: '#94a3b8',
          500: '#64748b',
          600: '#475569',
          700: '#334155',
          800: '#1e293b',
          900: '#0f172a',
          950: '#030712',
        },
        // Blue and Purple accents (from design_system.md)
        blue: {
          500: '#3b82f6',
          600: '#2563eb',
        },
        purple: {
          500: '#8b5cf6',
          600: '#7c3aed',
        },
        // Green success and Red error (from design_system.md)
        green: {
          400: '#6ee7b7',
          500: '#10b981',
          600: '#059669',
        },
        red: {
          400: '#fca5a5',
          500: '#ef4444',
          600: '#dc2626',
        },
        // Semantic color aliases (from design-tokens.md)
        brand: {
          primary: 'var(--color-brand-primary)',
          'primary-hover': 'var(--color-brand-primary-hover)',
          'primary-active': 'var(--color-brand-primary-active)',
          'primary-subtle': 'var(--color-brand-primary-subtle)',
          'primary-border': 'var(--color-brand-primary-border)',
        },
        status: {
          success: 'var(--color-status-success)',
          'success-bg': 'var(--color-status-success-bg)',
          'success-text': 'var(--color-status-success-text)',
          'success-border': 'var(--color-status-success-border)',
          running: 'var(--color-status-running)',
          'running-bg': 'var(--color-status-running-bg)',
          'running-text': 'var(--color-status-running-text)',
          'running-border': 'var(--color-status-running-border)',
          pending: 'var(--color-status-pending)',
          'pending-bg': 'var(--color-status-pending-bg)',
          'pending-text': 'var(--color-status-pending-text)',
          'pending-border': 'var(--color-status-pending-border)',
          failed: 'var(--color-status-failed)',
          'failed-bg': 'var(--color-status-failed-bg)',
          'failed-text': 'var(--color-status-failed-text)',
          'failed-border': 'var(--color-status-failed-border)',
          escalated: 'var(--color-status-escalated)',
          'escalated-bg': 'var(--color-status-escalated-bg)',
          'escalated-text': 'var(--color-status-escalated-text)',
          'escalated-border': 'var(--color-status-escalated-border)',
          info: 'var(--color-status-info)',
          'info-bg': 'var(--color-status-info-bg)',
          'info-text': 'var(--color-status-info-text)',
          'info-border': 'var(--color-status-info-border)',
        },
        agent: {
          thinking: 'var(--color-agent-thinking)',
          'thinking-bg': 'var(--color-agent-thinking-bg)',
          executing: 'var(--color-agent-executing)',
          'executing-bg': 'var(--color-agent-executing-bg)',
          waiting: 'var(--color-agent-waiting)',
          'waiting-bg': 'var(--color-agent-waiting-bg)',
          done: 'var(--color-agent-done)',
          'done-bg': 'var(--color-agent-done-bg)',
          error: 'var(--color-agent-error)',
          'error-bg': 'var(--color-agent-error-bg)',
        },
      },
      borderRadius: {
        'sm': '4px',
        'md': '6px',
        'lg': '8px',
        'xl': '12px',
        '2xl': '16px',
        '3xl': '24px',
        'full': '9999px',
      },
      fontFamily: {
        sans: ['Inter', '-apple-system', 'BlinkMacSystemFont', '"Segoe UI"', 'sans-serif'],
        mono: ['"JetBrains Mono"', '"Fira Code"', '"Cascadia Code"', 'monospace'],
      },
      fontSize: {
        'display': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em' }],
        'display-sm': ['40px', { lineHeight: '48px', letterSpacing: '-0.015em' }],
        'heading-xl': ['32px', { lineHeight: '40px' }],
        'heading-lg': ['24px', { lineHeight: '32px' }],
        'heading-md': ['20px', { lineHeight: '28px' }],
        'heading-sm': ['18px', { lineHeight: '24px' }],
        'body-xl': ['18px', { lineHeight: '28px' }],
        'body-md': ['16px', { lineHeight: '24px' }],
        'body-sm': ['14px', { lineHeight: '20px' }],
        'body-xs': ['12px', { lineHeight: '16px' }],
        'code': ['14px', { lineHeight: '20px', fontFamily: 'JetBrains Mono, monospace' }],
        'code-sm': ['12px', { lineHeight: '16px', fontFamily: 'JetBrains Mono, monospace' }],
        'label': ['14px', { lineHeight: '20px', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'overline': ['11px', { lineHeight: '16px', letterSpacing: '0.08em', fontWeight: '500' }],
        'xs': ['12px', { lineHeight: '16px' }],
        'sm': ['14px', { lineHeight: '20px' }],
        'base': ['16px', { lineHeight: '24px' }],
        'lg': ['18px', { lineHeight: '28px' }],
        'xl': ['20px', { lineHeight: '28px' }],
        '2xl': ['24px', { lineHeight: '32px' }],
        '3xl': ['30px', { lineHeight: '38px' }],
        '4xl': ['36px', { lineHeight: '44px' }],
        '5xl': ['48px', { lineHeight: '56px' }],
      },
      fontWeight: {
        'medium': '500',
        'regular': '400',
        'semibold': '600',
        'bold': '700',
        'black': '900',
      },
      opacity: {
        'overlay': 'var(--opacity-overlay)',
        'header': 'var(--opacity-header)',
        'surface': 'var(--opacity-surface)',
        'accent': 'var(--opacity-accent)',
      },
      boxShadow: {
        'sm': '0 1px 2px 0 rgb(0 0 0 / 0.05)',
        'md': '0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)',
        'orange-glow': '0 0 0 3px rgba(249, 115, 22, 0.2)',
        'xl': '0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)',
        'lg': '0 25px 50px -12px rgb(0 0 0 / 0.25)',
      },
      animation: {
        'typewriter': 'typing 30ms steps(1, end)',
        'cursor-blink': 'blink 530ms step-end infinite',
        // Agent state animations (from interaction-specs.md)
        'pulse-agent': 'pulse-agent 2s ease-in-out infinite',
        'pulse-cta': 'pulse-cta 2s ease-in-out infinite',
        'shimmer': 'shimmer 1.5s ease-in-out infinite',
        'typing-bounce': 'typing-bounce 0.6s ease-in-out infinite',
        'shake': 'shake 0.5s ease-in-out',
        'pop-in': 'pop-in 0.2s ease-out',
      },
      keyframes: {
        typing: {
          from: { width: '0' },
          to: { width: '100%' },
        },
        blink: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0' },
        },
        // Agent state animations (from interaction-specs.md)
        'pulse-agent': {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.7' },
        },
        'pulse-cta': {
          '0%, 100%': { transform: 'scale(1)', boxShadow: '0 0 0 0 rgba(249, 115, 22, 0.4)' },
          '50%': { transform: 'scale(1.02)', boxShadow: '0 0 0 8px rgba(249, 115, 22, 0)' },
        },
        'shimmer': {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        'typing-bounce': {
          '0%, 60%, 100%': { transform: 'translateY(0)' },
          '30%': { transform: 'translateY(-6px)' },
        },
        'shake': {
          '0%, 100%': { transform: 'translateX(0)' },
          '25%': { transform: 'translateX(-4px)' },
          '75%': { transform: 'translateX(4px)' },
        },
        'pop-in': {
          '0%': { transform: 'scale(0.9)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
      }
    }
  },
  plugins: [],
};