#!/usr/bin/env python3
"""
fetch-openbao-env.py
====================
Runtime script deployed by Ansible.
Queries OpenBao KV v2 at all seeded paths and generates a unified .env file
at /home/mkanavi/docker/iacgenie/.env for Docker Compose to consume.

All secrets are retrieved from OpenBao using the admin token stored
in the init_keys.json or from environment variable OPENBAO_TOKEN.

Usage: python3 fetch-openbao-env.py
"""

import json
import os
import sys
import urllib.request
import urllib.error
from datetime import datetime


# =====================
# Configuration
# =====================
OPENBAO_ADDR = os.getenv("OPENBAO_ADDR", "http://127.0.0.1:8200")
OUTPUT_PATH = "/home/mkanavi/docker/iacgenie/.env"
TOKEN_PATH = "/home/mkanavi/docker/iacgenie/data/openbao_raft/init_keys.json"

# All KV paths to fetch (matching openbao-secrets role)
KV_PATHS = [
    "iacgenie/kv/data/postgres",
    "iacgenie/kv/data/redis",
    "iacgenie/kv/data/minio",
    "iacgenie/kv/data/keycloak_admin",
    "iacgenie/kv/data/keycloak_db",
    "iacgenie/kv/data/gitea_db",
    "iacgenie/kv/data/gitea_admin",
    "iacgenie/kv/data/lightserp",
    "iacgenie/kv/data/jwt",
    "iacgenie/kv/data/cloudflare",
    "iacgenie/kv/data/grafana",
    "iacgenie/kv/data/searxng",
    "iacgenie/kv/data/nsqd",
    "iacgenie/kv/data/smtp",
]


def get_token():
    """Get OpenBao admin token from init_keys.json or env var."""
    # Try environment variable first
    token = os.getenv("OPENBAO_ADMIN_TOKEN")
    if token:
        return token

    # Try reading from init_keys.json
    try:
        with open(TOKEN_PATH, "r") as f:
            data = json.load(f)
            return data.get("root_token")
    except (FileNotFoundError, json.JSONDecodeError):
        print("[WARN] Could not read init_keys.json, no OPENBAO_ADMIN_TOKEN set")
        return None


def read_kv(path, token):
    """Read a secret from OpenBao KV v2."""
    url = f"{OPENBAO_ADDR}/v1/{path}"
    req = urllib.request.Request(url, headers={"X-Vault-Token": token})
    try:
        with urllib.request.urlopen(req, timeout=10) as resp:
            data = json.loads(resp.read().decode())
            return data.get("data", {}).get("data", {})
    except urllib.error.HTTPError as e:
        if e.code == 404:
            return None
        print(f"[WARN] Failed to read {path}: {e.code} {e.reason}")
        return None
    except Exception as e:
        print(f"[ERROR] Unexpected error reading {path}: {e}")
        return None


def build_database_url(postgres_data):
    """Build DATABASE_URL from postgres KV data."""
    user = postgres_data.get("POSTGRES_USER", "iacgenie_pg")
    password = postgres_data.get("POSTGRES_PASSWORD", "")
    db = postgres_data.get("POSTGRES_DB", "iacgenie")
    return f"postgresql://{user}:{password}@postgres:5432/{db}"


def generate_env(token):
    """Generate the unified .env file from OpenBao KV."""
    env_vars = {}

    print(f"[INFO] Fetching secrets from OpenBao at {OPENBAO_ADDR}")

    for kv_path in KV_PATHS:
        data = read_kv(kv_path, token)
        if data:
            print(f"[OK] {kv_path}")
            # Flatten nested data to ENV vars
            for key, value in data.items():
                env_vars[key] = str(value)
        else:
            print(f"[SKIP] {kv_path} (not found or unreadable)")

    # Build database URL from postgres data
    if "POSTGRES_USER" in env_vars:
        pg_data = env_vars
        env_vars["DATABASE_URL"] = build_database_url(env_vars)

    # Build redis URL
    if "REDIS_PASSWORD" in env_vars:
        env_vars["REDIS_URL"] = f"redis://:${env_vars['REDIS_PASSWORD']}@redis:6379/0"

    # Write .env file
    try:
        with open(OUTPUT_PATH, "w") as f:
            f.write(f"# Unified environment — generated by fetch-openbao-env.py at {datetime.utcnow().isoformat()}\n")
            f.write(f"# Managed by Ansible — do not edit manually\n")
            f.write(f"# All secrets from OpenBao KV\n\n")

            for key in sorted(env_vars.keys()):
                value = env_vars[key]
                f.write(f"{key}={value}\n")

        print(f"\n[OK] .env written to {OUTPUT_PATH} ({len(env_vars)} variables)")

        # Set restrictive permissions
        os.chmod(OUTPUT_PATH, 0o600)
        print(f"[OK] File permissions set to 0600")

    except IOError as e:
        print(f"[ERROR] Failed to write {OUTPUT_PATH}: {e}")
        sys.exit(1)

    return env_vars


def main():
    token = get_token()
    if not token:
        print("[ERROR] No OpenBao token available. Cannot fetch secrets.")
        sys.exit(1)

    env_vars = generate_env(token)
    if not env_vars:
        print("[ERROR] No secrets fetched from OpenBao.")
        sys.exit(1)


if __name__ == "__main__":
    main()
