#!/usr/bin/env python3
"""Fetch secrets from OpenBao KV v2 and generate a .env file."""
import json
import os
import ssl
import urllib.request
import urllib.error
from datetime import datetime, timezone


# =====================
# Configuration
# =====================
OPENBAO_ADDR = os.getenv("OPENBAO_ADDR", "http://127.0.0.1:8200")
OUTPUT_PATH = "/home/mkanavi/docker/iacgenie/.env"
TOKEN_PATH = "/home/mkanavi/docker/iacgenie/openbao_raft/init_keys.json"
SSL_SKIP_VERIFY = True

# All KV paths to fetch (matching openbao-secrets role)
KV_PATHS = [
    "iacgenie/kv/data/postgres",
    "iacgenie/kv/data/redis",
    "iacgenie/kv/data/minio",
    "iacgenie/kv/data/keycloak_admin",
    "iacgenie/kv/data/keycloak_db",
    "iacgenie/kv/data/gitea_db",
    "iacgenie/kv/data/gitea_admin",
    "iacgenie/kv/data/lightserp",
    "iacgenie/kv/data/jwt",
    "iacgenie/kv/data/cloudflare",
    "iacgenie/kv/data/grafana",
    "iacgenie/kv/data/searxng",
    "iacgenie/kv/data/nsqd",
    "iacgenie/kv/data/smtp",
]


def get_token():
    """Get OpenBao admin token from init_keys.json or env var."""
    # Try environment variable first
    token = os.getenv("OPENBAO_ADMIN_TOKEN")
    if token:
        return token

    # Try reading from init_keys.json
    try:
        with open(TOKEN_PATH, "r") as f:
            data = json.load(f)
            return data.get("root_token")
    except (FileNotFoundError, json.JSONDecodeError):
        print("[WARN] Could not read init_keys.json, no OPENBAO_ADMIN_TOKEN set")
        return None


def build_ssl_context():
    """Build SSL context, optionally skipping verification."""
    if SSL_SKIP_VERIFY:
        return ssl._create_unverified_context()
    return ssl.create_default_context()


def read_kv(engine, path, token):
    """Read a secret from OpenBao KV v2."""
    ctx = build_ssl_context()
    # KV v2 requires: /v1/{engine}/data/{path}
    url = f"{OPENBAO_ADDR}/v1/{engine}/data/{path}"
    req = urllib.request.Request(url, headers={"X-Vault-Token": token})
    try:
        with urllib.request.urlopen(req, context=ctx, timeout=10) as resp:
            data = json.loads(resp.read().decode())
            return data.get("data", {}).get("data", {})
    except urllib.error.HTTPError as e:
        if e.code == 404:
            return None
        print(f"[WARN] Failed to read {path}: {e.code} {e.reason}")
        return None
    except Exception as e:
        print(f"[ERROR] Unexpected error reading {path}: {e}")
        return None


def build_database_url(pg):
    """Build DATABASE_URL from postgres KV data."""
    return f"postgresql://{pg.get('POSTGRES_USER', 'iacgenie_pg')}:{pg.get('POSTGRES_PASSWORD', '')}@postgres:5432/{pg.get('POSTGRES_DB', 'iacgenie')}"


def generate_env(token):
    """Generate the unified .env content."""
    env_vars = {}
    fetched_paths = []

    print(f"[INFO] Fetching secrets from OpenBao at {OPENBAO_ADDR}")

    # iacgenie KV paths
    for path in [
        "kv/data/postgres",
        "kv/data/redis",
        "kv/data/minio",
        "kv/data/keycloak_admin",
        "kv/data/keycloak_db",
        "kv/data/gitea_db",
        "kv/data/gitea_admin",
        "kv/data/lightserp",
        "kv/data/jwt",
        "kv/data/cloudflare",
        "kv/data/grafana",
        "kv/data/searxng",
        "kv/data/nsqd",
        "kv/data/smtp",
    ]:
        data = read_kv("iacgenie", path, token)
        if data:
            env_vars.update(data)
            fetched_paths.append(path)
            print(f"[OK] iacgenie/{path}")
        else:
            print(f"[SKIP] iacgenie/{path} (not found or unreadable)")

    # lightserp KV paths
    for path in [
        "data/config/lightserp_database_url",
        "data/config/lightserp_api_secret",
        "data/config/lightserp_keycloak_client_secret",
        "data/config/redis_url",
        "data/config/minio_access_key",
        "data/config/minio_secret_key",
    ]:
        data = read_kv("lightserp", path, token)
        if data:
            # Map to env var names
            env_vars[data.get("key", path).replace("data/config/", "").replace("_", "").upper()] = data.get("value", "")
            fetched_paths.append(path)
            print(f"[OK] lightserp/{path}")
        else:
            print(f"[SKIP] lightserp/{path} (not found or unreadable)")

    # Build composite URLs
    if "POSTGRES_USER" in env_vars:
        pg_data = env_vars
        env_vars["DATABASE_URL"] = build_database_url(pg_data)

    if "REDIS_PASSWORD" in env_vars:
        env_vars["REDIS_URL"] = f"redis://:${env_vars['REDIS_PASSWORD']}@redis:6379/0"

    # Add OpenBao address
    env_vars["OPENBAO_ADDR"] = OPENBAO_ADDR

    print(f"\n[FETCHED] {len(fetched_paths)}/{len(KV_PATHS)} paths from OpenBao")
    return env_vars


def write_env(env_vars):
    """Write the .env file."""
    timestamp = datetime.now(timezone.utc).isoformat()
    lines = [
        "# Unified environment — generated by fetch-openbao-env.py",
        f"# Generated at: {timestamp}",
        "# WARNING: This file is auto-generated. Do not edit manually.",
        "# Regenerate by running: python3 fetch-openbao-env.py",
        "#",
        "",
    ]

    # Sort keys for consistency
    for key in sorted(env_vars.keys()):
        value = env_vars[key]
        if value:  # Skip empty values
            lines.append(f"{key}={value}")
        else:
            lines.append(f"{key}=")

    content = "\n".join(lines) + "\n"

    # Write file with restricted permissions
    fd = os.open(OUTPUT_PATH, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    try:
        os.write(fd, content.encode())
    finally:
        os.close(fd)

    return len(env_vars)


def main():
    token = get_token()
    if not token:
        print("[ERROR] No OpenBao token available. Cannot fetch secrets.")
        exit(1)

    env_vars = generate_env(token)
    if not env_vars:
        print("[ERROR] No secrets fetched from OpenBao.")
        exit(1)

    count = write_env(env_vars)
    print(f"[OK] .env written to {OUTPUT_PATH} ({count} variables)")
    print(f"[OK] File permissions set to 0600")


if __name__ == "__main__":
    main()
