---
- name: Reload docker compose
  ansible.builtin.command: "docker compose -f /home/mkanavi/docker/iacgenie/docker-compose.yml up -d"

- name: Wait for containers to be healthy
  ansible.builtin.command: "docker compose -f /home/mkanavi/docker/iacgenie/docker-compose.yml ps"
  register: _compose_status
  changed_when: false
  retries: 10
  delay: 15
  until: "'unhealthy' not in _compose_status.stdout"
