export type ModelCapability = 'vision' | 'code' | 'reasoning' | 'function-calling' | 'embedding';

export interface ModelDefinition {
  id: string;
  displayName: string;
  contextWindow: number;
  maxOutputTokens?: number;
  capabilities: ModelCapability[];
  tier: 'recommended' | 'standard' | 'legacy' | 'preview';
  costTier?: 'low' | 'medium' | 'high';
  latencyTier?: 'fast' | 'medium' | 'slow';
  releaseDate?: string;
  deprecated?: boolean;
  notes?: string;
}

export interface AdvancedConfig {
  max_tokens: number;
  temperature: number;
  timeout: number;
  retry_attempts: number;
  retry_delay: number;
  headers: Record<string, string>;
  metadata: Record<string, unknown>;
}

export const MODELS: Record<string, ModelDefinition[]> = {
  openai: [
    {
      id: 'gpt-4o',
      displayName: 'GPT-4o',
      contextWindow: 128000,
      maxOutputTokens: 16384,
      capabilities: ['vision', 'code', 'function-calling'],
      tier: 'recommended',
      costTier: 'high',
      latencyTier: 'medium',
      notes: 'Best for complex IaC generation',
    },
    {
      id: 'gpt-4o-mini',
      displayName: 'GPT-4o mini',
      contextWindow: 128000,
      maxOutputTokens: 16384,
      capabilities: ['vision', 'code', 'function-calling'],
      tier: 'recommended',
      costTier: 'low',
      latencyTier: 'fast',
      notes: 'Fast and cost-efficient',
    },
    {
      id: 'o1-preview',
      displayName: 'o1-preview',
      contextWindow: 128000,
      maxOutputTokens: 32768,
      capabilities: ['reasoning', 'code'],
      tier: 'preview',
      costTier: 'high',
      latencyTier: 'slow',
      notes: 'Best reasoning for complex architectures',
    },
    {
      id: 'o1-mini',
      displayName: 'o1-mini',
      contextWindow: 128000,
      maxOutputTokens: 65536,
      capabilities: ['reasoning', 'code'],
      tier: 'preview',
      costTier: 'medium',
      latencyTier: 'medium',
    },
    {
      id: 'gpt-4-turbo',
      displayName: 'GPT-4 Turbo',
      contextWindow: 128000,
      maxOutputTokens: 4096,
      capabilities: ['vision', 'code', 'function-calling'],
      tier: 'standard',
      costTier: 'high',
      latencyTier: 'medium',
    },
    {
      id: 'gpt-3.5-turbo',
      displayName: 'GPT-3.5 Turbo',
      contextWindow: 16385,
      maxOutputTokens: 4096,
      capabilities: ['code'],
      tier: 'legacy',
      costTier: 'low',
      latencyTier: 'fast',
    },
  ],
  anthropic: [
    {
      id: 'claude-3-5-sonnet-20241022',
      displayName: 'Claude 3.5 Sonnet',
      contextWindow: 200000,
      maxOutputTokens: 8192,
      capabilities: ['vision', 'code', 'reasoning'],
      tier: 'recommended',
      costTier: 'medium',
      latencyTier: 'medium',
      notes: 'Top-tier coding + reasoning',
    },
    {
      id: 'claude-3-5-haiku-20241022',
      displayName: 'Claude 3.5 Haiku',
      contextWindow: 200000,
      maxOutputTokens: 8192,
      capabilities: ['code'],
      tier: 'recommended',
      costTier: 'low',
      latencyTier: 'fast',
      notes: 'Fast and affordable',
    },
    {
      id: 'claude-3-opus-20240229',
      displayName: 'Claude 3 Opus',
      contextWindow: 200000,
      maxOutputTokens: 4096,
      capabilities: ['vision', 'code', 'reasoning'],
      tier: 'standard',
      costTier: 'high',
      latencyTier: 'slow',
    },
    {
      id: 'claude-3-haiku-20240307',
      displayName: 'Claude 3 Haiku',
      contextWindow: 200000,
      maxOutputTokens: 4096,
      capabilities: ['code'],
      tier: 'legacy',
      costTier: 'low',
      latencyTier: 'fast',
    },
  ],
  google: [
    {
      id: 'gemini-2.5-flash-preview-05-20',
      displayName: 'Gemini 2.5 Flash',
      contextWindow: 1000000,
      maxOutputTokens: 65536,
      capabilities: ['vision', 'code', 'reasoning', 'function-calling'],
      tier: 'recommended',
      costTier: 'low',
      latencyTier: 'fast',
      notes: 'Excellent speed-quality balance',
    },
    {
      id: 'gemini-2.5-pro-preview-05-06',
      displayName: 'Gemini 2.5 Pro',
      contextWindow: 1000000,
      maxOutputTokens: 65536,
      capabilities: ['vision', 'code', 'reasoning', 'function-calling'],
      tier: 'recommended',
      costTier: 'high',
      latencyTier: 'medium',
      notes: 'Best for complex IaC with 1M context',
    },
    {
      id: 'gemini-1.5-pro',
      displayName: 'Gemini 1.5 Pro',
      contextWindow: 2000000,
      maxOutputTokens: 8192,
      capabilities: ['vision', 'code', 'function-calling'],
      tier: 'standard',
      costTier: 'medium',
      latencyTier: 'medium',
    },
    {
      id: 'gemini-1.5-flash',
      displayName: 'Gemini 1.5 Flash',
      contextWindow: 1000000,
      maxOutputTokens: 8192,
      capabilities: ['vision', 'code'],
      tier: 'standard',
      costTier: 'low',
      latencyTier: 'fast',
    },
  ],
  groq: [
    {
      id: 'llama-3.3-70b-versatile',
      displayName: 'Llama 3.3 70B',
      contextWindow: 128000,
      maxOutputTokens: 32768,
      capabilities: ['code'],
      tier: 'recommended',
      costTier: 'low',
      latencyTier: 'fast',
      notes: 'Ultra-fast, free tier available',
    },
    {
      id: 'mixtral-8x7b-32768',
      displayName: 'Mixtral 8x7B',
      contextWindow: 32768,
      maxOutputTokens: 32768,
      capabilities: ['code'],
      tier: 'standard',
      costTier: 'low',
      latencyTier: 'fast',
    },
    {
      id: 'gemma2-9b-it',
      displayName: 'Gemma 2 9B',
      contextWindow: 8192,
      maxOutputTokens: 8192,
      capabilities: ['code'],
      tier: 'standard',
      costTier: 'low',
      latencyTier: 'fast',
    },
  ],
  mistral: [
    {
      id: 'mistral-large-latest',
      displayName: 'Mistral Large',
      contextWindow: 128000,
      maxOutputTokens: 8192,
      capabilities: ['code', 'function-calling'],
      tier: 'recommended',
      costTier: 'medium',
      latencyTier: 'medium',
    },
    {
      id: 'codestral-latest',
      displayName: 'Codestral',
      contextWindow: 32768,
      maxOutputTokens: 8192,
      capabilities: ['code'],
      tier: 'recommended',
      costTier: 'medium',
      latencyTier: 'fast',
      notes: 'Specialized for code generation',
    },
    {
      id: 'mistral-small-latest',
      displayName: 'Mistral Small',
      contextWindow: 32768,
      maxOutputTokens: 8192,
      capabilities: ['code'],
      tier: 'standard',
      costTier: 'low',
      latencyTier: 'fast',
    },
  ],
  deepseek: [
    {
      id: 'deepseek-chat',
      displayName: 'DeepSeek V3',
      contextWindow: 64000,
      maxOutputTokens: 8192,
      capabilities: ['code', 'reasoning'],
      tier: 'recommended',
      costTier: 'low',
      latencyTier: 'medium',
      notes: 'Excellent code generation',
    },
    {
      id: 'deepseek-reasoner',
      displayName: 'DeepSeek R1',
      contextWindow: 64000,
      maxOutputTokens: 8192,
      capabilities: ['reasoning', 'code'],
      tier: 'recommended',
      costTier: 'low',
      latencyTier: 'slow',
      notes: 'Chain-of-thought reasoning',
    },
  ],
  cohere: [
    {
      id: 'command-r-plus',
      displayName: 'Command R+',
      contextWindow: 128000,
      maxOutputTokens: 4096,
      capabilities: ['code', 'function-calling'],
      tier: 'recommended',
      costTier: 'medium',
      latencyTier: 'medium',
    },
    {
      id: 'command-r',
      displayName: 'Command R',
      contextWindow: 128000,
      maxOutputTokens: 4096,
      capabilities: ['code'],
      tier: 'standard',
      costTier: 'low',
      latencyTier: 'fast',
    },
  ],
  xai: [
    {
      id: 'grok-2-1212',
      displayName: 'Grok 2',
      contextWindow: 131072,
      maxOutputTokens: 8192,
      capabilities: ['code', 'vision'],
      tier: 'recommended',
      costTier: 'medium',
      latencyTier: 'medium',
    },
  ],
  perplexity: [
    {
      id: 'sonar-pro',
      displayName: 'Sonar Pro',
      contextWindow: 200000,
      maxOutputTokens: 8192,
      capabilities: ['reasoning', 'code'],
      tier: 'recommended',
      costTier: 'medium',
      latencyTier: 'medium',
      notes: 'Web-grounded search + generation',
    },
    {
      id: 'sonar-huge',
      displayName: 'Sonar Huge',
      contextWindow: 127072,
      maxOutputTokens: 8192,
      capabilities: ['reasoning'],
      tier: 'standard',
      costTier: 'high',
      latencyTier: 'slow',
    },
  ],
  openrouter: [
    {
      id: 'openai/gpt-4o',
      displayName: 'GPT-4o (via OpenRouter)',
      contextWindow: 128000,
      maxOutputTokens: 16384,
      capabilities: ['vision', 'code'],
      tier: 'recommended',
    },
    {
      id: 'anthropic/claude-3-5-sonnet',
      displayName: 'Claude 3.5 Sonnet (via OpenRouter)',
      contextWindow: 200000,
      maxOutputTokens: 8192,
      capabilities: ['vision', 'code', 'reasoning'],
      tier: 'recommended',
    },
    {
      id: 'meta-llama/llama-3.3-70b-instruct',
      displayName: 'Llama 3.3 70B (via OpenRouter)',
      contextWindow: 128000,
      maxOutputTokens: 4096,
      capabilities: ['code'],
      tier: 'standard',
    },
  ],
  ollama: [
    {
      id: 'llama3.3',
      displayName: 'Llama 3.3',
      contextWindow: 128000,
      capabilities: ['code'],
      tier: 'recommended',
      costTier: 'low',
      notes: 'Run locally — free',
    },
    {
      id: 'codellama',
      displayName: 'Code Llama',
      contextWindow: 16384,
      capabilities: ['code'],
      tier: 'recommended',
      notes: 'Specialized for code generation',
    },
    {
      id: 'mistral',
      displayName: 'Mistral 7B',
      contextWindow: 32768,
      capabilities: ['code'],
      tier: 'standard',
    },
    {
      id: 'qwen2.5-coder',
      displayName: 'Qwen 2.5 Coder',
      contextWindow: 32768,
      capabilities: ['code'],
      tier: 'standard',
    },
  ],
  lmstudio: [],
  custom: [
    {
      id: 'custom-model',
      displayName: 'Custom Model (specify below)',
      contextWindow: 8192,
      capabilities: [],
      tier: 'standard',
      notes: 'Enter any model name supported by your endpoint',
    },
  ],
  fireworks: [
    {
      id: 'accounts/fireworks/models/llama-v3p3-70b-instruct',
      displayName: 'Llama 3.3 70B',
      contextWindow: 131072,
      capabilities: ['code'],
      tier: 'recommended',
      costTier: 'low',
      latencyTier: 'fast',
    },
    {
      id: 'accounts/fireworks/models/deepseek-v3',
      displayName: 'DeepSeek V3',
      contextWindow: 65536,
      capabilities: ['code', 'reasoning'],
      tier: 'recommended',
      costTier: 'low',
    },
  ],
  together: [
    {
      id: 'meta-llama/Llama-3-70b-chat-hf',
      displayName: 'Llama 3 70B',
      contextWindow: 8000,
      capabilities: ['code'],
      tier: 'recommended',
    },
    {
      id: 'Qwen/Qwen2.5-72B-Instruct-Turbo',
      displayName: 'Qwen 2.5 72B',
      contextWindow: 32768,
      capabilities: ['code'],
      tier: 'recommended',
    },
  ],
};

export const DEFAULT_CONFIGS: Record<string, Partial<AdvancedConfig>> = {
  openai:       { max_tokens: 16384, temperature: 0.1, timeout: 120, retry_attempts: 3, retry_delay: 1.0 },
  anthropic:    { max_tokens: 8192,  temperature: 0.1, timeout: 120, retry_attempts: 3, retry_delay: 1.0 },
  google:       { max_tokens: 8192,  temperature: 0.1, timeout: 120, retry_attempts: 3, retry_delay: 1.0 },
  groq:         { max_tokens: 32768, temperature: 0.1, timeout: 60,  retry_attempts: 2, retry_delay: 0.5 },
  mistral:      { max_tokens: 8192,  temperature: 0.1, timeout: 120, retry_attempts: 3, retry_delay: 1.0 },
  deepseek:     { max_tokens: 8192,  temperature: 0.1, timeout: 120, retry_attempts: 3, retry_delay: 1.0 },
  cohere:       { max_tokens: 4096,  temperature: 0.1, timeout: 120, retry_attempts: 3, retry_delay: 1.0 },
  xai:          { max_tokens: 8192,  temperature: 0.1, timeout: 120, retry_attempts: 3, retry_delay: 1.0 },
  perplexity:   { max_tokens: 8192,  temperature: 0.1, timeout: 120, retry_attempts: 3, retry_delay: 1.0 },
  openrouter:   { max_tokens: 8192,  temperature: 0.1, timeout: 120, retry_attempts: 3, retry_delay: 1.0 },
  ollama:       { max_tokens: 8192,  temperature: 0.1, timeout: 300, retry_attempts: 2, retry_delay: 2.0 },
  lmstudio:     { max_tokens: 8192,  temperature: 0.1, timeout: 300, retry_attempts: 2, retry_delay: 2.0 },
  fireworks:    { max_tokens: 16384, temperature: 0.1, timeout: 60,  retry_attempts: 2, retry_delay: 0.5 },
  together:     { max_tokens: 4096,  temperature: 0.1, timeout: 120, retry_attempts: 3, retry_delay: 1.0 },
  custom:       { max_tokens: 8192,  temperature: 0.1, timeout: 120, retry_attempts: 3, retry_delay: 1.0 },
};
