export interface ProviderConfig {
  id: string;
  name: string;
  description: string;
  logoUrl?: string;
  category: 'cloud' | 'aggregator' | 'local' | 'enterprise';
  badge?: { label: string; color: 'orange' | 'blue' | 'green' | 'purple' | 'gray' };
  tier?: 'popular' | 'fast' | 'enterprise' | 'local' | 'gateway';
  defaultBaseUrl: string;
  supportsApiKey: boolean;
  requiresRegion?: boolean;
  requiresEndpointTemplate?: boolean;
  docsUrl?: string | null;
  keyPrefix?: string;
  keyHint?: string;
  apiVersion?: string;
}

export const PROVIDERS: ProviderConfig[] = [
  // ─── Cloud Providers ────────────────────────────────────────────────────
  {
    id: 'openai',
    name: 'OpenAI',
    description: 'GPT-4o, o1-preview, GPT-4o mini',
    category: 'cloud',
    tier: 'popular',
    badge: { label: 'Popular', color: 'orange' },
    defaultBaseUrl: 'https://api.openai.com/v1/chat/completions',
    supportsApiKey: true,
    docsUrl: 'https://platform.openai.com/docs',
    keyPrefix: 'sk-',
    keyHint: 'Starts with sk- or sk-proj-',
  },
  {
    id: 'anthropic',
    name: 'Anthropic',
    description: 'Claude 3.5 Sonnet, Claude 3 Haiku, Claude 3 Opus',
    category: 'cloud',
    tier: 'popular',
    badge: { label: 'Popular', color: 'orange' },
    defaultBaseUrl: 'https://api.anthropic.com/v1/messages',
    supportsApiKey: true,
    docsUrl: 'https://docs.anthropic.com',
    keyPrefix: 'sk-ant-',
    keyHint: 'Starts with sk-ant-...',
    apiVersion: '2023-06-01',
  },
  {
    id: 'google',
    name: 'Google AI',
    description: 'Gemini 2.5 Flash, Gemini 2.5 Pro, Gemini 1.5 Pro',
    category: 'cloud',
    tier: 'popular',
    badge: { label: 'Popular', color: 'orange' },
    defaultBaseUrl: 'https://generativelanguage.googleapis.com/v1beta/models',
    supportsApiKey: true,
    docsUrl: 'https://ai.google.dev/docs',
    keyHint: 'Google AI Studio API key (AIza...)',
  },
  {
    id: 'groq',
    name: 'Groq',
    description: 'Llama 3.3 70B, Mixtral 8x7B — ultra-fast inference',
    category: 'cloud',
    tier: 'fast',
    badge: { label: 'Fast ⚡', color: 'blue' },
    defaultBaseUrl: 'https://api.groq.com/openai/v1/chat/completions',
    supportsApiKey: true,
    docsUrl: 'https://console.groq.com/docs',
    keyPrefix: 'gsk_',
    keyHint: 'Starts with gsk_...',
  },
  {
    id: 'mistral',
    name: 'Mistral AI',
    description: 'Mistral Large, Mistral Small, Codestral',
    category: 'cloud',
    tier: 'popular',
    badge: { label: 'EU Data', color: 'purple' },
    defaultBaseUrl: 'https://api.mistral.ai/v1/chat/completions',
    supportsApiKey: true,
    docsUrl: 'https://docs.mistral.ai',
    keyHint: 'Mistral API key',
  },
  {
    id: 'cohere',
    name: 'Cohere',
    description: 'Command R+, Command R, Embed v3',
    category: 'cloud',
    tier: 'enterprise',
    badge: { label: 'Enterprise', color: 'gray' },
    defaultBaseUrl: 'https://api.cohere.com/v1/chat',
    supportsApiKey: true,
    docsUrl: 'https://docs.cohere.com',
    keyHint: 'Cohere API key',
  },
  {
    id: 'deepseek',
    name: 'DeepSeek',
    description: 'DeepSeek-V3, DeepSeek-R1 — top-tier reasoning',
    category: 'cloud',
    tier: 'popular',
    badge: { label: 'Reasoning', color: 'purple' },
    defaultBaseUrl: 'https://api.deepseek.com/chat/completions',
    supportsApiKey: true,
    docsUrl: 'https://platform.deepseek.com/api-docs',
    keyHint: 'DeepSeek API key',
  },
  {
    id: 'xai',
    name: 'xAI',
    description: 'Grok-2, Grok-1.5 — by Elon Musk\'s xAI',
    category: 'cloud',
    tier: 'popular',
    badge: { label: 'Grok', color: 'gray' },
    defaultBaseUrl: 'https://api.x.ai/v1/chat/completions',
    supportsApiKey: true,
    docsUrl: 'https://docs.x.ai',
    keyHint: 'xAI API key',
  },
  {
    id: 'perplexity',
    name: 'Perplexity',
    description: 'Sonar Pro, Sonar Huge — web-grounded models',
    category: 'cloud',
    tier: 'popular',
    badge: { label: 'Web Search', color: 'blue' },
    defaultBaseUrl: 'https://api.perplexity.ai/chat/completions',
    supportsApiKey: true,
    docsUrl: 'https://docs.perplexity.ai',
    keyPrefix: 'pplx-',
    keyHint: 'Starts with pplx-...',
  },
  {
    id: 'azure-openai',
    name: 'Azure OpenAI',
    description: 'GPT-4o, GPT-4 Turbo — via Microsoft Azure',
    category: 'enterprise',
    tier: 'enterprise',
    badge: { label: 'Enterprise', color: 'blue' },
    defaultBaseUrl: 'https://{resource}.openai.azure.com/openai/deployments/{deployment}/chat/completions?api-version=2024-08-01-preview',
    supportsApiKey: true,
    requiresEndpointTemplate: true,
    docsUrl: 'https://learn.microsoft.com/en-us/azure/ai-services/openai',
    keyHint: 'Azure OpenAI API key',
  },
  {
    id: 'aws-bedrock',
    name: 'AWS Bedrock',
    description: 'Claude, Llama, Titan — via AWS Bedrock',
    category: 'enterprise',
    tier: 'enterprise',
    badge: { label: 'AWS', color: 'orange' },
    defaultBaseUrl: 'https://bedrock-runtime.{region}.amazonaws.com',
    supportsApiKey: false,
    requiresRegion: true,
    docsUrl: 'https://docs.aws.amazon.com/bedrock',
    keyHint: 'Uses AWS access key / IAM credentials',
  },
  {
    id: 'fireworks',
    name: 'Fireworks AI',
    description: 'Llama 3.3, Mixtral, DeepSeek — fast inference',
    category: 'cloud',
    tier: 'fast',
    badge: { label: 'Fast ⚡', color: 'blue' },
    defaultBaseUrl: 'https://api.fireworks.ai/inference/v1/chat/completions',
    supportsApiKey: true,
    docsUrl: 'https://docs.fireworks.ai',
    keyPrefix: 'fw-',
    keyHint: 'Starts with fw-...',
  },
  {
    id: 'together',
    name: 'Together AI',
    description: 'Llama 3.3, Qwen, Mistral — open model hosting',
    category: 'aggregator',
    tier: 'popular',
    badge: { label: 'Open 🔓', color: 'green' },
    defaultBaseUrl: 'https://api.together.xyz/v1/chat/completions',
    supportsApiKey: true,
    docsUrl: 'https://docs.together.ai',
    keyHint: 'Together AI API key',
  },
  // ─── Aggregators ────────────────────────────────────────────────────────
  {
    id: 'openrouter',
    name: 'OpenRouter',
    description: '200+ models from all providers via one API key',
    category: 'aggregator',
    tier: 'gateway',
    badge: { label: 'Gateway ◈', color: 'purple' },
    defaultBaseUrl: 'https://openrouter.ai/api/v1/chat/completions',
    supportsApiKey: true,
    docsUrl: 'https://openrouter.ai/docs',
    keyPrefix: 'sk-or-',
    keyHint: 'Starts with sk-or-...',
  },
  // ─── Local / Self-Hosted ─────────────────────────────────────────────────
  {
    id: 'ollama',
    name: 'Ollama',
    description: 'Run Llama, Mistral, CodeLlama locally',
    category: 'local',
    tier: 'local',
    badge: { label: 'Local 💻', color: 'gray' },
    defaultBaseUrl: 'http://localhost:11434/v1/chat/completions',
    supportsApiKey: false,
    docsUrl: 'https://ollama.ai/docs',
    keyHint: 'No API key required for local Ollama',
  },
  {
    id: 'lmstudio',
    name: 'LM Studio',
    description: 'Run any GGUF model locally via LM Studio',
    category: 'local',
    tier: 'local',
    badge: { label: 'Local 💻', color: 'gray' },
    defaultBaseUrl: 'http://localhost:1234/v1/chat/completions',
    supportsApiKey: false,
    docsUrl: 'https://lmstudio.ai/docs',
    keyHint: 'No API key required for local LM Studio',
  },
  {
    id: 'custom',
    name: 'Custom / OpenAI-Compatible',
    description: 'Any OpenAI-compatible endpoint (vLLM, LocalAI, etc.)',
    category: 'local',
    tier: 'local',
    badge: { label: 'Custom ⚙', color: 'gray' },
    defaultBaseUrl: 'https://your-endpoint.com/v1/chat/completions',
    supportsApiKey: true,
    docsUrl: null,
    keyHint: 'API key if required by your endpoint',
  },
];

export const PROVIDER_CATEGORIES = [
  {
    label: 'Cloud Providers',
    providers: ['openai', 'anthropic', 'google', 'groq', 'mistral', 'cohere', 'deepseek', 'xai', 'perplexity', 'fireworks'],
  },
  {
    label: 'Enterprise',
    providers: ['azure-openai', 'aws-bedrock'],
  },
  {
    label: 'Aggregators & Routers',
    providers: ['openrouter', 'together'],
  },
  {
    label: 'Local & Self-Hosted',
    providers: ['ollama', 'lmstudio', 'custom'],
  },
];
