---
# Create default teams for each organization

- name: "10.12 | Gitea orgs | Get org team list"
  ansible.builtin.uri:
    url: "{{ gitea_api_url }}/api/v1/orgs/{{ target_org.org_name }}/teams"
    method: GET
    headers:
      Authorization: "token {{ gitea_api_token }}"
    status_code: [200]
  register: org_teams
  changed_when: false

- name: "10.12 | Gitea orgs | Create teams"
  ansible.builtin.uri:
    url: "{{ gitea_api_url }}/api/v1/orgs/{{ target_org.org_name }}/teams"
    method: POST
    headers:
      Authorization: "token {{ gitea_api_token }}"
      Content-Type: application/json
    body_format: json
    body:
      name: "{{ item.name }}"
      privilege: "{{ item.permission | default('read') }}"
      can_create_repository: false
      top_level_only: true
    status_code: [201]
  loop: "{{ target_org.teams }}"
  loop_control:
    label: "{{ item.name }}"
  register: team_created
  when:
    - item.name not in ((org_teams.json | default([])) | map(attribute='name') | list)
  changed_when: true
