---
- name: "Health check security services"
  ansible.builtin.uri:
    url: http://127.0.0.1:3310/
    status_code: 200
    method: GET
    timeout: 5
  ignore_errors: true
  register: clamav_health
  retries: 3
  delay: 10

- name: "Health check security services"
  ansible.builtin.uri:
    url: http://127.0.0.1:8080/v1/status
    status_code:
      - 200
      - 404
    method: GET
    timeout: 5
  ignore_errors: true
  register: crowdsec_health
  retries: 3
  delay: 10
