---
# Common role - Handlers
- name: Restart sshd
  ansible.builtin.service:
    name: sshd
    state: restarted

- name: Reload systemd and restart sshd
  ansible.builtin.systemd:
    name: sshd
    state: restarted
    daemon_reload: yes

- name: Restart fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: restarted

- name: Log ufw_status
  ansible.builtin.debug:
    msg: "UFW Status: {{ ufw_status.stdout }}"
